const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.video,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Video: 0},
	{Sprite9: 0},
	{Bullet: 0},
	{Sine: 0},
	{Sine2: 0},
	{Sprite10: 0},
	{Particles: 0},
	{scorebubble: 0},
	{Video2: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Text: 0},
	{materi: 0},
	{DragDrop: 0},
	{TiledBackground: 0},
	{Sprite13: 0},
	{TiledBackground2: 0},
	{Sprite14: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	scorebubble: class extends self.ITextInstance {},
	Video2: class extends self.IWorldInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	materi: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite14: class extends self.ISpriteInstance {}
}